package com.nivara.app.data.security

import android.security.keystore.KeyPermanentlyInvalidatedException
import com.nivara.app.domain.security.CryptographicFailure
import com.nivara.app.domain.security.EncryptionContext
import java.security.InvalidAlgorithmParameterException
import java.security.InvalidKeyException
import javax.crypto.AEADBadTagException
import javax.crypto.BadPaddingException
import javax.crypto.Cipher
import javax.crypto.IllegalBlockSizeException
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Nivara's versioned encrypted envelope, version 1.
 *
 * ```
 * offset  0        4        5          6          7         8        9            21
 *         | magic  | version| keyScheme| algorithm| contextTag| reserved| nonce (12) | ciphertext+tag |
 * ```
 *
 * - The magic, version, key scheme, algorithm and purpose tag are bound into the GCM associated
 *   data, so none of them can be edited without breaking the tag.
 * - The nonce lives in the header and must be unique per key; callers never choose it.
 * - The 128-bit authentication tag is JCA's own representation: `AES/GCM/NoPadding` appends it to
 *   the ciphertext, so it is not stored twice.
 *
 * The byte layout and its parsing rules are specified in `docs/crypto/envelope-format.md` and are
 * verified byte for byte against an independent implementation in the unit tests.
 *
 * This class is the only place that touches `Cipher` for symmetric encryption. Everything else in
 * Nivara goes through [com.nivara.app.domain.security.EncryptionService], which cannot be asked to
 * use a fixed nonce, an unauthenticated mode or a non-256-bit key.
 */
internal object EncryptedEnvelope {

    private val MAGIC = "NIVR".toByteArray(Charsets.US_ASCII)
    private const val MAGIC_SIZE = 4

    const val VERSION: Int = 1
    const val KEY_SCHEME_ANDROID_KEYSTORE: Int = 1
    const val ALGORITHM_AES_256_GCM: Int = 1

    const val KEY_SIZE_BITS: Int = 256
    const val KEY_SIZE_BYTES: Int = KEY_SIZE_BITS / 8
    const val NONCE_LENGTH: Int = 12
    const val TAG_LENGTH_BITS: Int = 128
    const val TAG_LENGTH_BYTES: Int = TAG_LENGTH_BITS / 8

    /** Everything up to and including the nonce. */
    const val HEADER_LENGTH: Int = MAGIC_SIZE + 5 + NONCE_LENGTH

    /** Magic, version, key scheme, algorithm and purpose tag: the authenticated context. */
    const val AAD_LENGTH: Int = MAGIC_SIZE + 4

    /** Header plus the smallest possible GCM tag. Anything shorter cannot be an envelope. */
    const val MINIMUM_LENGTH: Int = HEADER_LENGTH + TAG_LENGTH_BYTES

    /**
     * Upper bound for a single-shot envelope (32 MiB).
     *
     * This API exists for metadata, keys and other small values. Large payloads are encrypted in
     * chunks by the vault's streaming layer, so a single envelope never has to be huge, and a
     * corrupt length field cannot make the app allocate arbitrarily much memory.
     */
    const val MAXIMUM_LENGTH: Int = 32 * 1024 * 1024

    private const val VERSION_OFFSET = 4
    private const val KEY_SCHEME_OFFSET = 5
    private const val ALGORITHM_OFFSET = 6
    private const val CONTEXT_OFFSET = 7
    private const val RESERVED_OFFSET = 8
    private const val NONCE_OFFSET = 9
    private const val RESERVED_VALUE = 0
    /** The only JCA transformation Nivara uses for symmetric encryption. */
    const val TRANSFORMATION: String = "AES/GCM/NoPadding"

    /** `true` when [bytes] starts with an envelope magic, without validating the rest. */
    fun hasMagic(bytes: ByteArray): Boolean = bytes.hasPrefix(MAGIC)

    /**
     * Builds a complete envelope. The caller supplies the nonce, which must be unique for the key
     * and is generated by [com.nivara.app.domain.security.SecureRandomGenerator] in production.
     */
    fun encrypt(
        plaintext: ByteArray,
        key: SecretKey,
        context: EncryptionContext,
        nonce: ByteArray,
    ): ByteArray {
        requireValidKey(key)
        if (nonce.size != NONCE_LENGTH) throw CryptographicFailure.InvalidParameters

        val header = header(context = context, nonce = nonce)
        val body = cipher(Cipher.ENCRYPT_MODE, key, nonce).run {
            updateAAD(header, 0, AAD_LENGTH)
            doFinal(plaintext)
        }

        val envelope = ByteArray(header.size + body.size)
        header.copyInto(envelope, 0)
        body.copyInto(envelope, header.size)
        return envelope
    }

    /**
     * Parses and decrypts an envelope.
     *
     * Structural validation happens before any decryption, and the tag is verified before any
     * plaintext is returned. Every rejection maps to a typed failure; there is no partial result
     * and no fallback to a different algorithm or key.
     */
    fun decrypt(
        envelope: ByteArray,
        key: SecretKey,
        expectedContext: EncryptionContext,
    ): ByteArray {
        validate(envelope, expectedContext)
        requireValidKey(key)

        val nonce = envelope.copyOfRange(NONCE_OFFSET, HEADER_LENGTH)
        val cipher = cipher(Cipher.DECRYPT_MODE, key, nonce)
        cipher.updateAAD(envelope, 0, AAD_LENGTH)

        return try {
            cipher.doFinal(envelope, HEADER_LENGTH, envelope.size - HEADER_LENGTH)
        } catch (badTag: AEADBadTagException) {
            // Wrong key, edited nonce, edited ciphertext, edited header, or a payload that was
            // created for a different purpose.
            throw CryptographicFailure.AuthenticationFailed
        } catch (badPadding: BadPaddingException) {
            // Some providers report a failed tag through the generic padding exception.
            throw CryptographicFailure.AuthenticationFailed
        } catch (shortInput: IllegalBlockSizeException) {
            // The ciphertext is shorter than the tag: the envelope is truncated.
            throw CryptographicFailure.MalformedEnvelope
        } catch (invalidKey: InvalidKeyException) {
            throw CryptographicFailure.InvalidKey
        }
    }

    /** Assembles the fixed header for [context] and [nonce]. */
    fun header(context: EncryptionContext, nonce: ByteArray): ByteArray {
        val header = ByteArray(HEADER_LENGTH)
        MAGIC.copyInto(header, 0)
        header[VERSION_OFFSET] = VERSION.toByte()
        header[KEY_SCHEME_OFFSET] = KEY_SCHEME_ANDROID_KEYSTORE.toByte()
        header[ALGORITHM_OFFSET] = ALGORITHM_AES_256_GCM.toByte()
        header[CONTEXT_OFFSET] = context.tag.toByte()
        header[RESERVED_OFFSET] = RESERVED_VALUE.toByte()
        nonce.copyInto(header, NONCE_OFFSET)
        return header
    }

    /**
     * Rejects anything that is not a well-formed, correctly-purposed envelope of a supported
     * version.
     */
    private fun validate(envelope: ByteArray, expectedContext: EncryptionContext) {
        if (envelope.size < MINIMUM_LENGTH || envelope.size > MAXIMUM_LENGTH) {
            throw CryptographicFailure.MalformedEnvelope
        }
        if (!envelope.hasPrefix(MAGIC)) {
            throw CryptographicFailure.UnsupportedEnvelope
        }
        if (envelope[VERSION_OFFSET].toInt() != VERSION) {
            throw CryptographicFailure.UnsupportedVersion
        }
        if (envelope[KEY_SCHEME_OFFSET].toInt() != KEY_SCHEME_ANDROID_KEYSTORE) {
            throw CryptographicFailure.UnsupportedKeyScheme
        }
        if (envelope[ALGORITHM_OFFSET].toInt() != ALGORITHM_AES_256_GCM) {
            throw CryptographicFailure.UnsupportedAlgorithm
        }
        val context = EncryptionContext.fromTag(envelope[CONTEXT_OFFSET].toInt() and 0xFF)
            ?: throw CryptographicFailure.UnsupportedContext
        if (envelope[RESERVED_OFFSET].toInt() != RESERVED_VALUE) {
            throw CryptographicFailure.MalformedEnvelope
        }
        if (context != expectedContext) {
            throw CryptographicFailure.ContextMismatch
        }
    }

    private fun cipher(mode: Int, key: SecretKey, nonce: ByteArray): Cipher {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        try {
            cipher.init(mode, key, GCMParameterSpec(TAG_LENGTH_BITS, nonce))
        } catch (invalidated: KeyPermanentlyInvalidatedException) {
            // The platform invalidated a keystore key (new biometric enrolment, screen lock removed).
            throw CryptographicFailure.KeyInvalidated
        } catch (invalidKey: InvalidKeyException) {
            throw CryptographicFailure.InvalidKey
        } catch (invalidSpec: InvalidAlgorithmParameterException) {
            throw CryptographicFailure.InvalidParameters
        }
        return cipher
    }

    private fun requireValidKey(key: SecretKey) {
        if (key.algorithm != "AES") {
            throw CryptographicFailure.InvalidKey
        }
        // Keystore keys report a null encoded form; their size is fixed at generation time.
        val encodedSize = key.encoded?.size ?: return
        if (encodedSize != KEY_SIZE_BYTES) {
            throw CryptographicFailure.InvalidKey
        }
    }
}
