package com.nivara.app.data.vault

import com.nivara.app.core.common.NivaraResult
import com.nivara.app.core.common.valueOrNull
import com.nivara.app.domain.security.ContentKeyWrapper
import com.nivara.app.domain.security.DeviceKeyStore
import com.nivara.app.domain.security.EncryptionContext
import com.nivara.app.domain.security.EncryptionKey
import com.nivara.app.domain.security.EncryptionService
import com.nivara.app.domain.security.SecureRandomGenerator
import com.nivara.app.domain.vault.VaultFailure
import com.nivara.app.domain.vault.VaultIdentity
import com.nivara.app.domain.vault.VaultLocation
import com.nivara.app.domain.vault.VaultLocationRead
import com.nivara.app.domain.vault.VaultLocationStore
import com.nivara.app.domain.vault.VaultRepository
import com.nivara.app.domain.vault.VaultState
import com.nivara.app.domain.vault.VaultUnreadableReason
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock

/**
 * Nivara's vault root: what is at it, and creating one at it.
 *
 * ### Where the cryptography comes from
 *
 * Nothing here implements a cipher, a KDF, a nonce or a key-store call. The vault key is generated by
 * [SecureRandomGenerator], wrapped by [ContentKeyWrapper], and the metadata payload is sealed by
 * [EncryptionService] under `EncryptionContext.VaultMetadata`. The wrapping key is a [DeviceKeyStore]
 * key that lives in the platform key store and cannot be exported — which is what lets Nivara open
 * its own vault metadata without the user's credential while keeping the vault key out of reach of
 * anything that merely copies the folder.
 *
 * ```
 *  device key (platform key store, alias nivara.vault.v1)
 *        └── wraps the vault key (256 random bits per vault)
 *                └── sealed into the metadata payload, which the envelope authenticates
 * ```
 *
 * A credential-derived wrapping and a recovery wrapping of the *same* vault key belong to the stages
 * that follow: re-wrapping a content key never touches the encrypted data, which is why the key
 * hierarchy is shaped this way. This stage has neither, and no path here touches a credential, a
 * session, a biometric or a counter.
 *
 * ### Two slots and a generation
 *
 * The storage Nivara uses for the vault cannot replace a document atomically, so the record is written
 * into the slot that is *not* the current one, and the generation inside the record decides which
 * slot wins:
 *
 * ```
 *  vault.0.nvm (generation 7)   vault.1.nvm (generation 6)   →  slot 0 is authoritative
 *  write slot 1 with generation 8                            →  slot 1 becomes authoritative
 *  delete slot 0 (after the new record has been read back)   →  slot 1 alone remains
 * ```
 *
 * An interrupted write can therefore only damage the slot that was not authoritative, and the
 * read-back verification below makes "committed" a fact about the bytes on the user's storage rather
 * than about a call that returned.
 *
 * ### What the reads are careful about
 *
 * * a folder with none of Nivara's structure in it is [VaultState.Missing] — a confident "no vault
 *   here";
 * * a structure that exists without a record is an initialization that did not finish, reported as an
 *   incomplete structure rather than as an empty vault;
 * * a record whose clear header cannot be read is **not** "no vault": it is damage, or a newer
 *   format, or a key that is gone, each reported as its own case;
 * * a record is accepted only when its authenticated payload agrees with its clear header, so editing
 *   the header to promote an older record makes that record invalid instead of authoritative;
 * * nothing is repaired, nothing is deleted and nothing is created while looking.
 *
 * ### Concurrency
 *
 * One lock covers reading and writing, so an inspection that runs while an initialization is in
 * progress sees the state before or after it and never a half-written vault, and two initializations
 * cannot race for the same root. There is no background work, no polling and no cache: every call
 * goes to the storage the user chose.
 */
internal class NivaraVaultRepository(
    private val locationStore: VaultLocationStore,
    private val storageFactory: (VaultLocation) -> VaultRootStorage,
    private val deviceKeyStore: DeviceKeyStore,
    private val contentKeyWrapper: ContentKeyWrapper,
    private val encryptionService: EncryptionService,
    private val random: SecureRandomGenerator,
    private val lock: Mutex = Mutex(),
) : VaultRepository, VaultKeyAccess {

    override suspend fun inspect(): VaultState = lock.withLock {
        when (val stored = locationStore.storedLocation()) {
            VaultLocationRead.None -> VaultState.NotConfigured
            VaultLocationRead.Unreadable -> VaultState.LocationUnknown
            is VaultLocationRead.Present -> stateOf(survey(stored.location))
        }
    }

    override suspend fun initialize(replaceUnreadable: Boolean): NivaraResult<Unit> = lock.withLock {
        val location = when (val stored = locationStore.storedLocation()) {
            VaultLocationRead.None -> return NivaraResult.Failure(VaultFailure.InvalidLocation)
            VaultLocationRead.Unreadable -> return NivaraResult.Failure(VaultFailure.LocationUnreadable)
            is VaultLocationRead.Present -> stored.location
        }

        val survey = survey(location)
        refusalToInitialize(survey, replaceUnreadable)?.let { refusal ->
            return NivaraResult.Failure(refusal)
        }
        createVault(location, survey)
    }

    override suspend fun <T> withVaultKey(
        block: suspend (location: VaultLocation, key: EncryptionKey) -> NivaraResult<T>,
    ): NivaraResult<T> {
        // The record is opened under the lock, so the key and the location come from one look at the
        // vault; the block then runs outside it, because an import can take minutes and reading the
        // vault's state must not wait for a file to be encrypted.
        val borrowed = lock.withLock { openWrappedKey() }
        val available = when (borrowed) {
            is Borrowed.Available -> borrowed
            is Borrowed.Refused -> return NivaraResult.Failure(borrowed.failure)
        }

        val vaultKey = contentKeyWrapper.unwrap(
            wrappedKey = available.wrappedKey,
            wrappingKey = available.wrappingKey,
            context = EncryptionContext.KeyWrapping,
        ).valueOrNull() ?: return NivaraResult.Failure(VaultFailure.KeyUnavailable)

        return try {
            block(available.location, vaultKey)
        } finally {
            // Cleared in every case: a caller that forgot, an exception on the way out, or a normal
            // return. The key never outlives the work it was borrowed for.
            (vaultKey as? EncryptionKey.InProcess)?.clear()
        }
    }

    /** What one attempt to reach the vault's key found. */
    private sealed interface Borrowed {

        data class Available(
            val location: VaultLocation,
            val wrappingKey: EncryptionKey,
            val wrappedKey: ByteArray,
        ) : Borrowed

        data class Refused(val failure: VaultFailure) : Borrowed
    }

    /**
     * Reads the newest record and its wrapped key, or says why it cannot.
     *
     * The same survey the rest of the repository uses, so "the vault is ready" means the same thing
     * here as it does on the screen: a structure that is there, a record that authenticates, and a
     * content area to put objects in.
     */
    private suspend fun openWrappedKey(): Borrowed {
        val location = when (val stored = locationStore.storedLocation()) {
            VaultLocationRead.None -> return Borrowed.Refused(VaultFailure.InvalidLocation)
            VaultLocationRead.Unreadable -> return Borrowed.Refused(VaultFailure.LocationUnreadable)
            is VaultLocationRead.Present -> stored.location
        }

        val survey = survey(location)
        val seen = when (survey) {
            is Survey.Problem -> return Borrowed.Refused(survey.failure)
            is Survey.Seen -> survey
        }
        if (!seen.contentAreaPresent) {
            // The record authenticates but the area its content belongs in is gone. That is an
            // incomplete structure, not an empty vault, and nothing may be imported into it.
            return Borrowed.Refused(
                VaultFailure.VaultUnreadable(VaultUnreadableReason.StructureIncomplete),
            )
        }
        val record = seen.records.maxByOrNull { candidate -> candidate.generation }
            ?: return Borrowed.Refused(
                VaultFailure.VaultUnreadable(VaultUnreadableReason.StructureIncomplete),
            )

        val wrappingKey = when (val key = deviceKeyStore.retrieveKey(WRAPPING_KEY_ALIAS)) {
            is NivaraResult.Success -> key.value
            is NivaraResult.Failure -> return Borrowed.Refused(VaultFailure.KeyUnavailable)
        }
        return Borrowed.Available(
            location = location,
            wrappingKey = wrappingKey,
            wrappedKey = record.wrappedKey,
        )
    }

    // ------------------------------------------------------------------ reading

    /**
     * Everything one look at the root found.
     *
     * Both [inspect] and [initialize] work from this, so the decision about whether a vault may be
     * created here is made from exactly the evidence the user is shown.
     */
    private sealed interface Survey {

        data class Seen(
            val records: List<Record>,
            val metadataAreaPresent: Boolean,
            val contentAreaPresent: Boolean,
            val unreadableVersion: Int?,
            val damaged: Boolean,
            val keyUnavailable: Boolean,
        ) : Survey

        data class Problem(val failure: VaultFailure) : Survey
    }

    /**
     * One metadata document: the slot it sits in, its generation, the identity it carries, and the
     * wrapped key it holds.
     *
     * The wrapped key is kept as it was authenticated rather than read again later: lending the key
     * must be the same act as opening the record, or a record could be opened for one generation and
     * lent against another.
     */
    private data class Record(
        val slot: String,
        val generation: Long,
        val identity: VaultIdentity,
        val wrappedKey: ByteArray,
    )

    private suspend fun survey(location: VaultLocation): Survey {
        val storage = storageFactory(location)

        val metadataArea = storage.metadataAreaExists()
        val metadataAreaPresent = metadataArea.valueOrNull()
            ?: return Survey.Problem(metadataArea.vaultFailureOf())
        val entries = storage.metadataEntries()
        val areaEntries = entries.valueOrNull() ?: return Survey.Problem(entries.vaultFailureOf())
        val contentArea = storage.contentAreaExists()
        val contentAreaPresent = contentArea.valueOrNull()
            ?: return Survey.Problem(contentArea.vaultFailureOf())

        val records = mutableListOf<Record>()
        var unreadableVersion: Int? = null
        var damaged = false
        var keyUnavailable = false

        for (entryName in areaEntries.filter { name -> name in VaultStructure.SLOT_NAMES }) {
            val bytes = storage.readMetadata(entryName).valueOrNull()
            if (bytes == null) {
                // A slot that cannot be read at all is damage, not an absence: something with a
                // slot's name is there, and Nivara cannot say what it holds.
                damaged = true
                continue
            }
            when (val header = VaultRecordCodec.readHeader(bytes)) {
                VaultRecordCodec.HeaderRead.NotAVaultRecord -> Unit // a foreign file in the area
                is VaultRecordCodec.HeaderRead.Unreadable -> {
                    val version = header.fileVersion
                    if (version != null && version != VaultRecordCodec.VERSION) {
                        unreadableVersion = version
                    } else {
                        damaged = true
                    }
                }
                is VaultRecordCodec.HeaderRead.Present ->
                    when (val opened = openRecord(entryName, bytes, header.header)) {
                        is OpenOutcome.Opened -> records += opened.record
                        OpenOutcome.KeyUnavailable -> keyUnavailable = true
                        OpenOutcome.Damaged -> damaged = true
                    }
            }
        }

        return Survey.Seen(
            records = records,
            metadataAreaPresent = metadataAreaPresent,
            contentAreaPresent = contentAreaPresent,
            unreadableVersion = unreadableVersion,
            damaged = damaged,
            keyUnavailable = keyUnavailable,
        )
    }

    private sealed interface OpenOutcome {
        data class Opened(val record: Record) : OpenOutcome
        data object KeyUnavailable : OpenOutcome
        data object Damaged : OpenOutcome
    }

    /**
     * Authenticates one record's payload and checks its agreement with the clear header.
     *
     * The generation is compared in both places on purpose. The clear header is not covered by the
     * envelope's authentication, so a record whose sealed payload disagrees with its own header is a
     * record somebody edited, and it is treated as damage rather than trusted.
     */
    private suspend fun openRecord(
        slot: String,
        bytes: ByteArray,
        header: VaultRecordCodec.Header,
    ): OpenOutcome {
        if (!VaultRecordCodec.isCompleteRecord(bytes)) return OpenOutcome.Damaged
        val wrappingKey = when (val key = deviceKeyStore.retrieveKey(WRAPPING_KEY_ALIAS)) {
            is NivaraResult.Success -> key.value
            is NivaraResult.Failure -> return OpenOutcome.KeyUnavailable
        }
        val payloadBytes = encryptionService.decrypt(
            envelope = VaultRecordCodec.envelopeOf(bytes),
            key = wrappingKey,
            context = EncryptionContext.VaultMetadata,
        ).valueOrNull() ?: return OpenOutcome.Damaged
        val payload = VaultRecordCodec.decodePayload(payloadBytes) ?: return OpenOutcome.Damaged
        if (payload.generation != header.generation) return OpenOutcome.Damaged
        if (payload.wrappedKey.isEmpty()) return OpenOutcome.Damaged
        return OpenOutcome.Opened(
            Record(
                slot = slot,
                generation = payload.generation,
                identity = payload.identity,
                wrappedKey = payload.wrappedKey,
            ),
        )
    }

    /** Turns a survey into the state the rest of the application reasons about. */
    private fun stateOf(survey: Survey): VaultState = when (survey) {
        is Survey.Problem -> when (val failure = survey.failure) {
            VaultFailure.AccessDenied, VaultFailure.InvalidLocation -> VaultState.AccessDenied
            is VaultFailure.VaultUnreadable -> VaultState.Unreadable(failure.reason)
            is VaultFailure.UnsupportedVersion -> VaultState.UnsupportedVersion(failure.fileVersion)
            else -> VaultState.Unavailable
        }

        is Survey.Seen -> {
            val record = survey.records.maxByOrNull { candidate -> candidate.generation }
            when {
                record != null && survey.contentAreaPresent -> VaultState.Ready(
                    identity = record.identity,
                    formatVersion = VaultRecordCodec.VERSION,
                )
                // The metadata authenticates, so this *is* a Nivara vault, and a part of it is
                // missing. That is neither an empty vault nor a valid one.
                record != null -> VaultState.Unreadable(VaultUnreadableReason.StructureIncomplete)
                survey.unreadableVersion != null ->
                    VaultState.UnsupportedVersion(survey.unreadableVersion)
                survey.keyUnavailable -> VaultState.Unreadable(VaultUnreadableReason.KeyUnavailable)
                survey.damaged -> VaultState.Unreadable(VaultUnreadableReason.MetadataDamaged)
                // Nivara's structure is there and holds no record: an initialization that did not
                // finish, which is a fact about this folder and not an absent vault.
                survey.metadataAreaPresent || survey.contentAreaPresent ->
                    VaultState.Unreadable(VaultUnreadableReason.StructureIncomplete)
                else -> VaultState.Missing
            }
        }
    }

    // ------------------------------------------------------------------ writing

    /** Why a vault may not be created here, or `null` when it may. */
    private fun refusalToInitialize(survey: Survey, replaceUnreadable: Boolean): VaultFailure? =
        when (survey) {
            is Survey.Problem -> survey.failure
            is Survey.Seen -> when {
                survey.records.isNotEmpty() -> VaultFailure.VaultAlreadyExists
                survey.unreadableVersion != null ->
                    VaultFailure.UnsupportedVersion(survey.unreadableVersion)
                // A structure with no record in it holds no key material, so completing it destroys
                // nothing and needs no confirmation. Damage and a lost key may still hold recoverable
                // material, so they are replaced only when the user has explicitly said so.
                survey.damaged || survey.keyUnavailable -> if (replaceUnreadable) {
                    null
                } else {
                    VaultFailure.VaultUnreadable(
                        if (survey.keyUnavailable) {
                            VaultUnreadableReason.KeyUnavailable
                        } else {
                            VaultUnreadableReason.MetadataDamaged
                        },
                    )
                }
                else -> null
            }
        }

    /**
     * Creates the vault: structure, key material, authenticated metadata — and nothing is reported as
     * done until the record on the user's own storage has been read back and opened.
     */
    private suspend fun createVault(location: VaultLocation, survey: Survey): NivaraResult<Unit> {
        val storage = storageFactory(location)

        if (storage.ensureMetadataArea() !is NivaraResult.Success) {
            return NivaraResult.Failure(VaultFailure.WriteFailed)
        }
        if (storage.ensureContentArea() !is NivaraResult.Success) {
            return NivaraResult.Failure(VaultFailure.WriteFailed)
        }

        val wrappingKey = when (val key = deviceKeyStore.getOrCreateKey(WRAPPING_KEY_ALIAS)) {
            is NivaraResult.Success -> key.value
            is NivaraResult.Failure -> return NivaraResult.Failure(VaultFailure.KeyUnavailable)
        }

        val vaultKey = EncryptionKey.fromRawBytes(
            material = random.nextKeyBytes(),
            label = VAULT_KEY_LABEL,
        )
        try {
            val wrappedKey = contentKeyWrapper.wrap(
                contentKey = vaultKey,
                wrappingKey = wrappingKey,
                context = EncryptionContext.KeyWrapping,
            ).valueOrNull() ?: return NivaraResult.Failure(VaultFailure.CryptographyFailed)

            // The wrapping is opened again here, before anything is committed: a vault whose key
            // material cannot be unwrapped on the device that created it only *looks* initialized,
            // and finding that out now costs a failure instead of the vault.
            if (!wrappedKeyCanBeRecovered(wrappedKey, wrappingKey, vaultKey)) {
                return NivaraResult.Failure(VaultFailure.CryptographyFailed)
            }

            return commitRecord(
                storage = storage,
                survey = survey,
                wrappedKey = wrappedKey,
                wrappingKey = wrappingKey,
                identity = VaultIdentity.create(random),
            )
        } finally {
            (vaultKey as? EncryptionKey.InProcess)?.clear()
        }
    }

    /**
     * Recommits the vault's own record for a vault whose key was recovered, not created.
     *
     * Recovery after a reinstall yields the vault's existing key and its existing identity, but the
     * record that held them was sealed under the installation that is gone. This writes the next
     * generation of that same record — the same identity, the key re-wrapped under this
     * installation's device key — through the exact two-slot, read-back-verified commit the vault's
     * creation uses. It creates nothing: no key, no identity, no content. It re-expresses the
     * installation-local wrapping of what is already there, which is what reconnecting *is*.
     */
    internal suspend fun reconnectRecord(
        location: VaultLocation,
        identity: VaultIdentity,
        wrappedKey: ByteArray,
        wrappingKey: EncryptionKey,
    ): NivaraResult<Unit> = lock.withLock {
        val storage = storageFactory(location)
        val survey = survey(location)
        if (survey is Survey.Problem) return NivaraResult.Failure(survey.failure)
        commitRecord(
            storage = storage,
            survey = survey,
            wrappedKey = wrappedKey,
            wrappingKey = wrappingKey,
            identity = identity,
        )
    }

    private suspend fun wrappedKeyCanBeRecovered(
        wrappedKey: ByteArray,
        wrappingKey: EncryptionKey,
        vaultKey: EncryptionKey,
    ): Boolean {
        val unwrapped = contentKeyWrapper.unwrap(
            wrappedKey = wrappedKey,
            wrappingKey = wrappingKey,
            context = EncryptionContext.KeyWrapping,
        ).valueOrNull() ?: return false
        val expected = (vaultKey as? EncryptionKey.InProcess)?.material
        val actual = (unwrapped as? EncryptionKey.InProcess)?.material
        val matches = expected != null && actual != null && expected.contentEquals(actual)
        (unwrapped as? EncryptionKey.InProcess)?.clear()
        return matches
    }

    /**
     * Seals the payload, writes the record into the free slot, validates it, and only then prunes the
     * slot that is no longer authoritative.
     *
     * The order matters at every step: the payload is authenticated before it is written; the record
     * goes into the slot a reader would *not* pick; the record is read back and opened before success
     * is reported; and the old record is deleted only once the new one has been proven readable. A
     * failure leaves the root either without a record — reporting an incomplete structure, which a
     * retry completes — or with the previous record untouched.
     */
    private suspend fun commitRecord(
        storage: VaultRootStorage,
        survey: Survey,
        wrappedKey: ByteArray,
        wrappingKey: EncryptionKey,
        identity: VaultIdentity,
    ): NivaraResult<Unit> {
        val existing = (survey as? Survey.Seen)?.records.orEmpty()
        val generation = (existing.maxOfOrNull { record -> record.generation } ?: 0L) +
            VaultRecordCodec.FIRST_GENERATION
        val currentSlot = existing.maxByOrNull { record -> record.generation }?.slot
        val targetSlot = if (currentSlot == null) {
            VaultStructure.SLOT_NAMES.first()
        } else {
            VaultStructure.SLOT_NAMES.first { name -> name != currentSlot }
        }

        val payload = VaultRecordCodec.encodePayload(
            generation = generation,
            identity = identity,
            wrappedKey = wrappedKey,
        )
        val envelope = encryptionService.encrypt(
            plaintext = payload,
            key = wrappingKey,
            context = EncryptionContext.VaultMetadata,
            clearPlaintextAfterUse = true,
        ).valueOrNull() ?: return NivaraResult.Failure(VaultFailure.CryptographyFailed)

        val record = VaultRecordCodec.encodeRecord(generation = generation, envelope = envelope)
        if (storage.writeMetadata(targetSlot, record) !is NivaraResult.Success) {
            // Nothing was committed: the slot is cleared so a retry starts from the same place, and
            // the failure is reported whatever the cleanup does.
            storage.deleteMetadata(targetSlot)
            return NivaraResult.Failure(VaultFailure.WriteFailed)
        }

        val readBack = storage.readMetadata(targetSlot).valueOrNull()
        if (readBack == null || !recordValidates(readBack, generation, identity, wrappingKey)) {
            // The bytes did not come back as they were written. That is not a vault, and it is not
            // reported as one: the record this attempt wrote is removed and the caller is told the
            // write could not be trusted.
            storage.deleteMetadata(targetSlot)
            return NivaraResult.Failure(VaultFailure.VerificationFailed)
        }

        // Only now is everything else pruned — stale records and unreadable leftovers alike. If a
        // deletion fails, the new record still wins on the next read by its generation, so the cleanup
        // is best effort rather than part of the commit.
        VaultStructure.SLOT_NAMES
            .filter { name -> name != targetSlot }
            .forEach { name -> storage.deleteMetadata(name) }
        return NivaraResult.Success(Unit)
    }

    /** Whether [bytes] is the record this attempt wrote, opened end to end. */
    private suspend fun recordValidates(
        bytes: ByteArray,
        generation: Long,
        identity: VaultIdentity,
        wrappingKey: EncryptionKey,
    ): Boolean {
        val header = VaultRecordCodec.readHeader(bytes)
        if (header !is VaultRecordCodec.HeaderRead.Present) return false
        if (header.header.generation != generation) return false
        val payloadBytes = encryptionService.decrypt(
            envelope = VaultRecordCodec.envelopeOf(bytes),
            key = wrappingKey,
            context = EncryptionContext.VaultMetadata,
        ).valueOrNull() ?: return false
        val payload = VaultRecordCodec.decodePayload(payloadBytes) ?: return false
        return payload.generation == generation &&
            payload.identity == identity &&
            payload.wrappedKey.isNotEmpty()
    }

    internal companion object {

        /**
         * The platform key that protects the vault's key material.
         *
         * Versioned like every other alias in the project, so a future change of key-material
         * semantics becomes a new alias rather than a silent reinterpretation of an existing one.
         * Reconnection re-wraps the recovered vault key under exactly this alias — the hierarchy is
         * not extended, only re-established for a fresh installation.
         */
        const val WRAPPING_KEY_ALIAS = "nivara.vault.v1"

        /** Non-secret label for the in-process vault key, used in diagnostics only. */
        const val VAULT_KEY_LABEL = "vault-key"
    }
}

/**
 * The vault-typed failure behind a storage call.
 *
 * The storage port is written to report typed failures, so this only has to recognise them; anything
 * else — which would mean an implementation broke the contract — is reported as unreachable storage
 * rather than being swallowed.
 */
private fun <T> NivaraResult<T>.vaultFailureOf(): VaultFailure = when (this) {
    is NivaraResult.Success -> VaultFailure.StorageUnavailable
    is NivaraResult.Failure -> error as? VaultFailure ?: VaultFailure.StorageUnavailable
}
